# -*- coding: utf-8 -*-
"""hw1_binary_hex_converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6XdQkWvB_neT9EQpqCZuaacT3rKXGwu
"""

number=input("十進位數字: ")
number=int(number)

two=0
if number>=2**7 and number<2**8:
  number-=2**7
  two+=10**7
if number>=2**6 and number<2**7:
  number-=2**6
  two+=10**6
if number>=2**5 and number<2**6:
  number-=2**5
  two+=10**5
if number>=2**4 and number<2**5:
  number-=2**4
  two+=10**4
if number>=2**3 and number<2**4:
  number-=2**3
  two+=10**3
if number>=2**2 and number<2**3:
  number-=2**2
  two+=10**2
if number>=2**1 and number<2**2:
  number-=2**1
  two+=10**1
if number>=2**0 and number<2**1:
  number-=2**0
  two+=10**0
print("二進位數字: ",two,sep="")

front=0
back=0
if two>=10**7 and two<10**8:
  two-=10**7
  front+=2**3
if two>=10**6 and two<10**7:
  two-=10**6
  front+=2**2
if two>=10**5 and two<10**6:
  two-=10**5
  front+=2**1
if two>=10**4 and two<10**5:
  two-=10**4
  front+=2**0
if two>=10**3 and two<10**4:
  two-=10**3
  back+=2**3
if two>=10**2 and two<10**3:
  two-=10**2
  back+=2**2
if two>=10**1 and two<10**2:
  two-=10**1
  back+=2**1
if two>=10**0 and two<10**1:
  two-=10**0
  back+=2**0

if front==10:
  front="A"
elif front==11:
  front="B"
elif front==12:
  front="C"
elif front==13:
  front="D"
elif front==14:
  front="E"
elif front==15:
  front="F"
else:
  front=str(front)

if back==10:
  back="A"
elif back==11:
  back="B"
elif back==12:
  back="C"
elif back==13:
  back="D"
elif back==14:
  back="E"
elif back==15:
  back="F"
else:
  back=str(back)

if front=="0":
  print("十六進位數字: "+back)
else:
  print("十六進位數字: "+front+back)